import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { NetworkDevice, NetworkFlow } from '@/types/sdms';
import { ReactFlow, Controls, Background, Node, Edge } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { AlertCircle, Activity, Network as NetworkIcon } from 'lucide-react';

// Mock data for network devices
const mockDevices: NetworkDevice[] = [
  { id: 'fw-01', name: 'Main Firewall', type: 'firewall', ip: '10.0.0.1', zone: 'dmz', status: 'online', lastSeen: new Date().toISOString() },
  { id: 'sw-01', name: 'Core Switch', type: 'switch', ip: '10.0.0.2', zone: 'internal', status: 'online', lastSeen: new Date().toISOString() },
  { id: 'rt-01', name: 'Primary Router', type: 'router', ip: '10.0.0.3', zone: 'internal', status: 'online', lastSeen: new Date().toISOString() },
  { id: 'vpn-01', name: 'VPN Gateway', type: 'vpn', ip: '10.0.0.4', zone: 'public', status: 'online', lastSeen: new Date().toISOString() },
  { id: 'srv-01', name: 'App Server 1', type: 'server', ip: '10.0.1.10', zone: 'internal', status: 'online', lastSeen: new Date().toISOString() },
  { id: 'srv-02', name: 'Database Server', type: 'server', ip: '10.0.1.11', zone: 'private', status: 'warning', lastSeen: new Date().toISOString() }
];

// Mock data for network flows
const mockFlows: NetworkFlow[] = [
  { id: 'flow-1', source: 'fw-01', target: 'sw-01', protocol: 'TCP', port: 443, bandwidth: '10 Mbps', latency: 2 },
  { id: 'flow-2', source: 'sw-01', target: 'rt-01', protocol: 'TCP', port: 80, bandwidth: '5 Mbps', latency: 1 },
  { id: 'flow-3', source: 'sw-01', target: 'srv-01', protocol: 'TCP', port: 22, bandwidth: '2 Mbps', latency: 3 },
  { id: 'flow-4', source: 'srv-01', target: 'srv-02', protocol: 'TCP', port: 3306, bandwidth: '8 Mbps', latency: 2 },
  { id: 'flow-5', source: 'vpn-01', target: 'fw-01', protocol: 'UDP', port: 1194, bandwidth: '1 Mbps', latency: 15 }
];

const NetworkTopology = () => {
  const [nodes, setNodes] = useState<Node[]>([]);
  const [edges, setEdges] = useState<Edge[]>([]);

  useEffect(() => {
    // Convert mock devices to ReactFlow nodes
    const flowNodes = mockDevices.map((device, index) => {
      // Create a layout with devices in a circle
      const angle = (index / mockDevices.length) * 2 * Math.PI;
      const radius = 200;
      const x = 300 + radius * Math.cos(angle);
      const y = 300 + radius * Math.sin(angle);
      
      let color;
      switch (device.status) {
        case 'online':
          color = '#10b981'; // green
          break;
        case 'warning':
          color = '#f59e0b'; // yellow
          break;
        case 'offline':
          color = '#ef4444'; // red
          break;
      }
      
      return {
        id: device.id,
        data: { label: device.name, device },
        position: { x, y },
        style: { 
          backgroundColor: color, 
          color: '#fff',
          border: '1px solid #e2e8f0',
          borderRadius: '8px',
          padding: '10px',
          width: 150,
          height: 60
        }
      };
    });
    
    // Convert mock flows to ReactFlow edges
    const flowEdges = mockFlows.map(flow => ({
      id: flow.id,
      source: flow.source,
      target: flow.target,
      label: `${flow.protocol}:${flow.port}`,
      animated: flow.latency > 10,
      style: { stroke: '#94a3b8' }
    }));
    
    setNodes(flowNodes);
    setEdges(flowEdges);
  }, []);

  return (
    <div className="space-y-6">
      <div className="text-lg font-medium">Network Topology & Flow Charts</div>
      <p className="text-muted-foreground">
        Interactive visualization of your network architecture generated by AI analysis.
      </p>
      
      <Tabs defaultValue="topology" className="h-[calc(100vh-300px)]">
        <TabsList>
          <TabsTrigger value="topology">Topology Map</TabsTrigger>
          <TabsTrigger value="flow">Data Flow</TabsTrigger>
          <TabsTrigger value="zones">Security Zones</TabsTrigger>
        </TabsList>
        
        <TabsContent value="topology" className="h-full">
          <Card className="h-full">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <NetworkIcon className="h-5 w-5" />
                <span>Network Topology Map</span>
              </CardTitle>
              <CardDescription>
                Auto-generated map of core network devices and connections
              </CardDescription>
            </CardHeader>
            <CardContent className="h-[calc(100%-80px)]">
              <div style={{ height: '100%', width: '100%' }}>
                <ReactFlow
                  nodes={nodes}
                  edges={edges}
                  fitView
                >
                  <Controls />
                  <Background />
                </ReactFlow>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="flow" className="h-full">
          <Card className="h-full">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-5 w-5" />
                <span>Data Flow Analysis</span>
              </CardTitle>
              <CardDescription>
                Real-time visualization of data flows between network components
              </CardDescription>
            </CardHeader>
            <CardContent className="h-[calc(100%-80px)]">
              <div className="flex items-center justify-center h-full">
                <div className="text-center p-6 max-w-md">
                  <AlertCircle className="h-10 w-10 text-amber-500 mx-auto mb-4" />
                  <h3 className="text-lg font-medium">Collecting Flow Data</h3>
                  <p className="text-muted-foreground mt-2">
                    The system is currently analyzing network traffic patterns. This may take a few minutes to complete.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="zones" className="h-full">
          <Card className="h-full">
            <CardHeader>
              <CardTitle>Security Zones Visualization</CardTitle>
              <CardDescription>
                Visual map of security zones and their relationships
              </CardDescription>
            </CardHeader>
            <CardContent className="h-[calc(100%-80px)]">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 h-full">
                <Card className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800">
                  <CardHeader>
                    <CardTitle className="text-md">DMZ</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">2 Devices</p>
                    <ul className="mt-2 space-y-1 text-sm">
                      <li>Main Firewall</li>
                      <li>Web Proxy</li>
                    </ul>
                  </CardContent>
                </Card>
                
                <Card className="bg-green-50 dark:bg-green-950 border-green-200 dark:border-green-800">
                  <CardHeader>
                    <CardTitle className="text-md">Internal</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">12 Devices</p>
                    <ul className="mt-2 space-y-1 text-sm">
                      <li>Core Switch</li>
                      <li>Primary Router</li>
                      <li>App Server 1</li>
                      <li>+9 More</li>
                    </ul>
                  </CardContent>
                </Card>
                
                <Card className="bg-purple-50 dark:bg-purple-950 border-purple-200 dark:border-purple-800">
                  <CardHeader>
                    <CardTitle className="text-md">Private</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">5 Devices</p>
                    <ul className="mt-2 space-y-1 text-sm">
                      <li>Database Server</li>
                      <li>Auth Server</li>
                      <li>+3 More</li>
                    </ul>
                  </CardContent>
                </Card>
                
                <Card className="bg-amber-50 dark:bg-amber-950 border-amber-200 dark:border-amber-800">
                  <CardHeader>
                    <CardTitle className="text-md">Public</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">3 Devices</p>
                    <ul className="mt-2 space-y-1 text-sm">
                      <li>VPN Gateway</li>
                      <li>Load Balancer</li>
                      <li>CDN Edge</li>
                    </ul>
                  </CardContent>
                </Card>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default NetworkTopology;
