
import { 
  PartnerInfo, 
  Deal, 
  Quote, 
  ClientTenant, 
  SupportTicket, 
  PartnerResource, 
  Certification,
  Commission
} from './types';

export const mockPartnerInfo: PartnerInfo = {
  id: 'partner-123',
  name: 'Secure MSP Solutions',
  tier: 'Certified',
  channelManager: {
    name: 'Alex Rodriguez',
    email: 'alex.rodriguez@avaron.com',
    phone: '(555) 123-4567',
  },
  metrics: {
    totalClients: 23,
    monthlyRecurringRevenue: 118600,
    commissionPaidYTD: 92400,
    nextTierThreshold: 500000,
    currentTierProgress: 320000,
  },
};

export const mockDeals: Deal[] = [
  {
    id: 'deal-101',
    businessName: 'Acme Healthcare',
    industry: 'Healthcare',
    contactName: 'Jane Smith',
    contactEmail: 'jane@acmehealthcare.com',
    estimatedSize: 50,
    requestedProducts: ['SMB', 'VaultID', 'Storage'],
    notes: 'Looking for compliance solutions with secure storage',
    registrationDate: '2023-06-15T14:22:10Z',
    expirationDate: '2023-09-15T14:22:10Z',
    status: 'Protected',
  },
  {
    id: 'deal-102',
    businessName: 'TechNova Inc',
    industry: 'Technology',
    contactName: 'Mike Williams',
    contactEmail: 'mike@technova.com',
    estimatedSize: 120,
    requestedProducts: ['Mid', 'AI', 'VaultID'],
    notes: 'Interested in AI capabilities and secure authentication',
    registrationDate: '2023-07-10T09:30:45Z',
    expirationDate: '2023-10-10T09:30:45Z',
    status: 'Protected',
  },
  {
    id: 'deal-103',
    businessName: 'Global Finance Group',
    industry: 'Finance',
    contactName: 'Sarah Johnson',
    contactEmail: 'sarah@gfgroup.com',
    estimatedSize: 200,
    requestedProducts: ['Enterprise', 'VaultID', 'AI', 'Storage'],
    notes: 'Need comprehensive security solution with AI threat detection',
    registrationDate: '2023-05-22T11:15:30Z',
    expirationDate: '2023-08-22T11:15:30Z',
    status: 'Converted',
  },
  {
    id: 'deal-104',
    businessName: 'Retail Solutions Co',
    industry: 'Retail',
    contactName: 'David Lee',
    contactEmail: 'david@retailsolutions.com',
    estimatedSize: 75,
    requestedProducts: ['Mid', 'Storage'],
    notes: 'Looking for data storage and backup solutions',
    registrationDate: '2023-08-01T16:45:20Z',
    expirationDate: '2023-11-01T16:45:20Z',
    status: 'Disputed',
  },
];

export const mockQuotes: Quote[] = [
  {
    id: 'quote-201',
    clientName: 'Acme Healthcare',
    createdDate: '2023-07-20T10:30:15Z',
    products: {
      hardware: ['Security Gateway X3', 'NAS Storage Unit'],
      supportTier: 'Premium',
      storage: 2,
      vaultID: 50,
      ai: true,
      tenantLicenses: 1,
    },
    pricing: {
      msrp: 35000,
      suggestedPrice: 31500,
      margin: 18,
      discount: 10,
    },
    status: 'Pending',
  },
  {
    id: 'quote-202',
    clientName: 'TechNova Inc',
    createdDate: '2023-08-05T14:22:30Z',
    products: {
      hardware: ['Security Gateway X5', 'AI Processing Node', 'Redundant Storage Array'],
      supportTier: 'Enterprise',
      storage: 5,
      vaultID: 125,
      ai: true,
      tenantLicenses: 1,
    },
    pricing: {
      msrp: 87500,
      suggestedPrice: 78750,
      margin: 22,
      discount: 10,
    },
    status: 'Won',
  },
  {
    id: 'quote-203',
    clientName: 'City Medical Center',
    createdDate: '2023-06-12T09:15:45Z',
    products: {
      hardware: ['Security Gateway X2', 'Compact NAS'],
      supportTier: 'Standard',
      storage: 1,
      vaultID: 25,
      ai: false,
      tenantLicenses: 1,
    },
    pricing: {
      msrp: 18500,
      suggestedPrice: 17575,
      margin: 15,
      discount: 5,
    },
    status: 'Lost',
  },
];

export const mockClientTenants: ClientTenant[] = [
  {
    id: 'tenant-301',
    name: 'Acme Healthcare',
    status: 'Active',
    userCount: 57,
    lastLogin: '2023-09-01T14:22:10Z',
    slaTier: 'Premium',
    lastTicket: {
      id: 'ticket-8721',
      summary: 'VPN Configuration Issue',
      status: 'In Progress',
    },
  },
  {
    id: 'tenant-302',
    name: 'TechNova Inc',
    status: 'Active',
    userCount: 132,
    lastLogin: '2023-09-02T10:15:33Z',
    slaTier: 'Enterprise',
    lastTicket: {
      id: 'ticket-8735',
      summary: 'AI Model Training Request',
      status: 'Pending',
    },
  },
  {
    id: 'tenant-303',
    name: 'Global Finance Group',
    status: 'Active',
    userCount: 215,
    lastLogin: '2023-09-02T16:40:22Z',
    slaTier: 'Enterprise',
    lastTicket: {
      id: 'ticket-8702',
      summary: 'Storage Expansion Request',
      status: 'Completed',
    },
  },
  {
    id: 'tenant-304',
    name: 'SmartTech Solutions',
    status: 'Pending',
    userCount: 42,
    lastLogin: '2023-08-28T11:05:18Z',
    slaTier: 'Standard',
    lastTicket: {
      id: 'ticket-8695',
      summary: 'Initial Setup Assistance',
      status: 'In Progress',
    },
  },
  {
    id: 'tenant-305',
    name: 'Educational Services Inc',
    status: 'Active',
    userCount: 88,
    lastLogin: '2023-09-02T09:30:45Z',
    slaTier: 'Premium',
    lastTicket: {
      id: 'ticket-8730',
      summary: 'License Renewal Question',
      status: 'Resolved',
    },
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'ticket-8721',
    clientName: 'Acme Healthcare',
    subject: 'VPN Configuration Issue',
    createdDate: '2023-08-30T13:45:22Z',
    status: 'In Progress',
    priority: 'Medium',
    lastUpdate: '2023-09-01T10:15:30Z',
    isEscalated: false,
  },
  {
    id: 'ticket-8735',
    clientName: 'TechNova Inc',
    subject: 'AI Model Training Request',
    createdDate: '2023-09-02T09:30:15Z',
    status: 'Pending',
    priority: 'Low',
    lastUpdate: '2023-09-02T09:30:15Z',
    isEscalated: false,
  },
  {
    id: 'ticket-8715',
    clientName: 'Global Finance Group',
    subject: 'Security Alert Investigation',
    createdDate: '2023-08-28T16:22:10Z',
    status: 'In Progress',
    priority: 'High',
    lastUpdate: '2023-09-01T14:10:45Z',
    isEscalated: true,
  },
  {
    id: 'ticket-8695',
    clientName: 'SmartTech Solutions',
    subject: 'Initial Setup Assistance',
    createdDate: '2023-08-25T11:05:18Z',
    status: 'In Progress',
    priority: 'Medium',
    lastUpdate: '2023-08-30T15:45:30Z',
    isEscalated: false,
  },
];

export const mockPartnerResources: PartnerResource[] = [
  {
    id: 'resource-401',
    title: 'Avaron Security Suite Overview',
    type: 'Collateral',
    description: 'One-pager overview of the complete Avaron security suite',
    fileUrl: '/resources/avaron-security-suite.pdf',
    dateAdded: '2023-05-10T09:00:00Z',
  },
  {
    id: 'resource-402',
    title: 'Healthcare Compliance Solution',
    type: 'Case Study',
    description: 'Case study on implementing Avaron in a healthcare environment',
    fileUrl: '/resources/healthcare-case-study.pdf',
    dateAdded: '2023-06-15T14:30:00Z',
  },
  {
    id: 'resource-403',
    title: 'Avaron vs. Competitors Comparison',
    type: 'Product Sheet',
    description: 'Feature comparison with Fortinet, Cisco, and other competitors',
    fileUrl: '/resources/competitor-comparison.pdf',
    dateAdded: '2023-07-22T11:45:00Z',
  },
  {
    id: 'resource-404',
    title: 'AI Security Demo',
    type: 'Video',
    description: 'Demo of AI-powered threat detection capabilities',
    fileUrl: '/resources/ai-security-demo.mp4',
    dateAdded: '2023-08-05T15:20:00Z',
  },
  {
    id: 'resource-405',
    title: 'Partner Program Benefits',
    type: 'Collateral',
    description: 'Overview of partner tiers and associated benefits',
    fileUrl: '/resources/partner-program-benefits.pdf',
    dateAdded: '2023-04-18T10:30:00Z',
  },
];

export const mockCertifications: Certification[] = [
  {
    id: 'cert-501',
    name: 'Avaron Sales Certification',
    description: 'Basic product knowledge and sales positioning',
    status: 'Completed',
    progress: 100,
    badgeUrl: '/certifications/sales-badge.png',
    linkedInUrl: 'https://linkedin.com/certification/avaron-sales',
    expirationDate: '2024-09-01T00:00:00Z',
  },
  {
    id: 'cert-502',
    name: 'Deployment Specialist',
    description: 'Technical implementation and deployment expertise',
    status: 'In Progress',
    progress: 65,
  },
  {
    id: 'cert-503',
    name: 'Compliance Auditor',
    description: 'Regulatory compliance and audit preparation',
    status: 'Not Started',
    progress: 0,
  },
  {
    id: 'cert-504',
    name: 'AI Systems Engineer',
    description: 'Advanced configuration of AI security features',
    status: 'In Progress',
    progress: 30,
  },
];

export const mockCommissions: Commission[] = [
  {
    id: 'comm-601',
    period: 'August 2023',
    clientName: 'TechNova Inc',
    productType: 'Enterprise Suite',
    revenue: 78750,
    commissionRate: 15,
    commissionAmount: 11812.5,
    status: 'Pending',
  },
  {
    id: 'comm-602',
    period: 'July 2023',
    clientName: 'Global Finance Group',
    productType: 'Enterprise Suite',
    revenue: 92500,
    commissionRate: 15,
    commissionAmount: 13875,
    status: 'Paid',
    paymentDate: '2023-08-15T00:00:00Z',
  },
  {
    id: 'comm-603',
    period: 'July 2023',
    clientName: 'Educational Services Inc',
    productType: 'Mid-Market Suite',
    revenue: 45000,
    commissionRate: 10,
    commissionAmount: 4500,
    status: 'Paid',
    paymentDate: '2023-08-15T00:00:00Z',
  },
  {
    id: 'comm-604',
    period: 'June 2023',
    clientName: 'City Medical Center',
    productType: 'SMB Suite',
    revenue: 22000,
    commissionRate: 10,
    commissionAmount: 2200,
    status: 'Paid',
    paymentDate: '2023-07-15T00:00:00Z',
  },
  {
    id: 'comm-605',
    period: 'June 2023',
    clientName: 'Acme Healthcare',
    productType: 'Mid-Market Suite',
    revenue: 31500,
    commissionRate: 10,
    commissionAmount: 3150,
    status: 'Paid',
    paymentDate: '2023-07-15T00:00:00Z',
  },
];
